### ISSUE TITLE
Nexmo requires api_key and api_secret not username and password

### ISSUE THREAD

**Issue by clphillips** [spantaleev/sms-sender#3]
According to the [Nexmo Documentation](https://docs.nexmo.com/api-ref/sms-api/request), sending an SMS message requires an **api_key** and **api_secret** parameter, **not** [username and password](https://github.com/spantaleev/sms-sender/blob/master/src/Devture/Component/SmsSender/Gateway/NexmoGateway.php#L22).

**Comment by spantaleev** [comment]
Thanks for noticing that!
Perhaps they'll stop supporting `username` and `password` some time in the future.
Version `1.0.1` contains the fix.
